package leetcode.bruteForce;

import java.util.HashMap;
import java.util.Map;

/*
Q.389 Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        Map<Character, Integer> usedCount = new HashMap<>();

        for (char c : s.toCharArray()) {
            usedCount.put(c, usedCount.getOrDefault(c, 0) + 1);
        }

        for (char c : t.toCharArray()) {
            if (!usedCount.containsKey(c)) return c;

            int remainCount = usedCount.get(c);

            if (remainCount == 0) return c;

            usedCount.put(c, remainCount - 1);
        }

        throw new IllegalArgumentException("");
    }
}

/*
class Solution {
    public char findTheDifference(String s, String t) {
        char c = 0;
        for(char cs : s.toCharArray()) c ^= cs;
        for(char ct : t.toCharArray()) c ^= ct;
        return c;
    }
}
 */